import 'package:flutter/material.dart';

import '../models/product.dart';

class ProductProvider with ChangeNotifier {
  final _products = [
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes1.jpg', name: 'Sapatos'),
    Product(image: 'assets/images/shoes2.jpg', name: 'Sapatos'),
  ];

  List<Product> get products => [..._products];
}
