// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmAFsgZT6BcdE1HcWq23bCh7YIqS5ytQY',
    appId: '1:962224246245:web:c17707039e35ca312d730c',
    messagingSenderId: '962224246245',
    projectId: 'agencetestebr',
    authDomain: 'agencetestebr.firebaseapp.com',
    storageBucket: 'agencetestebr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_WrTmjrMHGaCB6KcB0bP4rV995VkhVPY',
    appId: '1:962224246245:android:ae90c2d323735ad82d730c',
    messagingSenderId: '962224246245',
    projectId: 'agencetestebr',
    storageBucket: 'agencetestebr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs3ffD8NqB3qybcKxQpouEXdt1e-DVP1Q',
    appId: '1:962224246245:ios:0e03226dac877b762d730c',
    messagingSenderId: '962224246245',
    projectId: 'agencetestebr',
    storageBucket: 'agencetestebr.appspot.com',
    iosClientId: '962224246245-26m0to88or697pvatl2suuat8andnscc.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenceteste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs3ffD8NqB3qybcKxQpouEXdt1e-DVP1Q',
    appId: '1:962224246245:ios:0e03226dac877b762d730c',
    messagingSenderId: '962224246245',
    projectId: 'agencetestebr',
    storageBucket: 'agencetestebr.appspot.com',
    iosClientId: '962224246245-26m0to88or697pvatl2suuat8andnscc.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenceteste',
  );
}
